int x;
int x[2];
int *x[2];
int f(int x, float *y);
int (*f)(int x, float *);
int (*f[2])(int x, float *);
string f(void);
int xArray[3];
int *xArray[3];
int (*pArray)[3];
int f(int x);
int *f(void);
int (*f)(int x);
int f(int xArray[3]);
int *f(int xArray[3], float *, char c);
int f(int x, float y, char c);
int *(*f)[3](int y);